### ISSUE TITLE
postcss import need works with postcss url

### ISSUE THREAD

**Issue by SirM2z** [vuejs-templates/webpack#1106]
Hi, I got error in last release

![](https://raw.githubusercontent.com/SirM2z/assets/master/image/vue_webpqck_err.png)

my css:

```css
@font-face {
  font-family: "iconfont";
  src: url('iconfont.eot?t=1510823274364'); /* IE9*/
  /* ... */
}
```

it is solved when I add `"postcss-url": {},` in `.postcssrc.js`

**Comment by LinusBorg** [comment]
Please provide  way to reproduce this for us, I can't tell what you did to get this error.

**Comment by SirM2z** [comment]
My directory

&nbsp;.
└── src
　　　├── App.vue
　　　└── assets
　　　　　　└── font
　　　　　　　　　├── iconfont.css
　　　　　　　　　└── iconfont.eot

In `App.vue`

```css
@import './assets/font/iconfont.css';
```

In `iconfont.css`

```css
@font-face {
  font-family: "iconfont";
  src: url('iconfont.eot?t=1510823274364'); /* IE9*/
  /* ... */
}
```
