### ISSUE TITLE
Docker Image for Testing

### ISSUE THREAD

**Issue by F1LT3R** [vuejs-templates/webpack#1300]
Hi there. I am wondering if anyone could point me to a docker image that will run these Nightwatch tests?

These Docker images fail for me on CircleCI.

- image: circleci/node:7.10
- image: karthikiyengar/node-nightwatch:0.0.1
- image: kenfehling/node-selenium-chrome

I am using the _out-of-the-box_ project that is installed when using `vue init webpack`, and selecting Jest and Nightwatch.

My `config.yml` looks like this:

```yml
# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # - image: circleci/node:7.10
      # - image: karthikiyengar/node-nightwatch:0.0.1
      - image: kenfehling/node-selenium-chrome

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: npm test
```

Repo: https://github.com/F1LT3R/vue-webpack-circleci-test
