### ISSUE TITLE
`npm run build` - The CSS file is uncompressed

### ISSUE THREAD

**Issue by limichange** [vuejs-templates/webpack#481]
run `npm run build`, and look at `dist/static/css/app.ba287ef4df4d02daad84183620c318c6.css`.

```css
#app {
  font-family: 'Avenir', Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}

h1[data-v-730cc838], h2[data-v-730cc838] {
  font-weight: normal;
}
ul[data-v-730cc838] {
  list-style-type: none;
  padding: 0;
}
li[data-v-730cc838] {
  display: inline-block;
  margin: 0 10px;
}
a[data-v-730cc838] {
  color: #42b983;
}

/*# sourceMappingURL=app.ba287ef4df4d02daad84183620c318c6.css.map*/
```

somebody konw why ?
