### ISSUE TITLE
Autoprefixer is only active for .vue files

### ISSUE THREAD

**Issue by fvsch** [vuejs-templates/webpack#600]
This seems to be the same bug as https://github.com/vuejs-templates/webpack/issues/85, which was closed because, I quote, "Autoprefixer is in the latest template release", but we don't get Autoprefixer working for CSS or SCSS files outside of `.vue` components.

Steps to reproduce:

```
vue init webpack postcss-test && cd postcss-test
npm install
npm install node-sass sass-loader --save-dev
```

Then create a few test stylesheets:

```css
/* src/assets/test1.css */
.test1 { display: flex; }
```

```scss
// src/assets/test2.scss
.test2 { display: flex; }
```

Finally, let's test a few ways to load these:

1. As entry points:

```js
// build/webpack.base.conf.js
...
module.exports = {
  entry: {
    app: './src/main.js',
    test1: './src/assets/test1.css',
    test2: './src/assets/test2.scss'
  },
  ...
}
```

Then `npm run build`. Results:

```css
/* dist/static/css/test1.ca0cd0e2b1b09d965f5ce5c21f1fc6e7.css */
.test1{display:flex}

/* dist/static/css/test2.4d716aeffa93f62596ef617b3129561c.css */
.test2{display:flex}
```

2. As JS imports:

```html
<!-- src/App.vue -->
<script>
import {} from './assets/test1.css'
import {} from './assets/test2.scss'
...
</script>
```

(Remove the entry points test before.) Then `npm run build`. Result:

```css
/* dist/static/css/app.4006533b8ed715dfd365cdd7a0b4f7be.css */
.test1,.test2{display:flex}
```

3. In style tags in components:

```html
<!-- src/App.vue -->
<style>
@import './assets/test1.css';
.test1b { display: flex; }
</style>

<style lang="scss">
@import './assets/test2.scss';
.test2b { display: flex; }
</style>
```

Result:

```css
/* dist/static/css/app.6c438b7dca17522bb707d18112b8cbcb.css */
.test1{display:flex}.test1b,.test2,.test2b{display:-webkit-box;display:-ms-flexbox;display:flex}
```

Conclusion: Autoprefixer is only used for style tags inside `.vue` components.
When using Sass or SCSS syntax and an external Sass/SCSS stylesheet, this can be used to apply Autoprefixer to code stored outside of components; the same trick does not work for CSS imports.

Was #85 closed based on a faulty assumption?

As a side note, debugging this issue proved difficult (for several team members) because this template comes with references to autoprefixer and postcss in two locations:

- `package.json` -> `"browserslist"` entry
- `.postcssrc.js`

But the config in `config` and `build` never references these locations, postcss or autoprefixer. It's all happening by magic, but only in very limited settings.

Maybe the brower list and postcss config should be moved to `build/vue-loader.conf.js`, if it only applies to vue-loader? As it is, it's sending the message that it's a project-wide config, but in practice it doesn't seem to be.

**Comment by fvsch** [comment]
Possible duplicate: https://github.com/vuejs-templates/webpack/issues/544

**Comment by cycold** [comment]
Yeah, I have the problem too. I have to add `postcss-loader` to loaders

Note: need to `yarn add postcss-loader -D` 

![qq20170317-094519](https://cloud.githubusercontent.com/assets/2446601/24025631/86368d26-0af6-11e7-951f-af6ef2b75b73.png)

**Comment by matheusgrieger** [comment]
Got this problem as well. Importing any SCSS file, though loads them correctly, does not autoprefix them.

But above solution by @cycold works like a charm, thank you!

**Comment by ozguruysal** [comment]
Yes the solution from @cycold works great. However you get a warning pointing to https://github.com/postcss/postcss-loader#sourcemap if you have `sourceMap` set to `false` in `config/index.js` that is the default setting.

Would be nice if this feature came out of the box as it's kinda expected result.

**Comment by KagamiChan** [comment]
In @cycold 's code other loaders are pushed to the `loaders` array, resulting something like [cssLoader, postcssLoader, ...otherStyleLoader], so I try inserting postcssLoader at last place.

My code is like this

```js
...
  var vueStyleLoader = {
    loader: 'vue-style-loader',
    options: {
      sourceMap: options.sourceMap
    }
  }

  // generate loader string to be used with extract text plugin
  function generateLoaders (loader, loaderOptions) {
    var loaders = [cssLoader]
    if (loader) {
      loaders.push({
        loader: loader + '-loader',
        options: Object.assign({}, loaderOptions, {
          sourceMap: options.sourceMap
        })
      })
    }

    loaders.push(postcssLoader)

...
```

**Comment by tfsimondouglas** [comment]
Any further developments to this? I have to suppport IE10.... :( 
Getting the same sourcemap issues as @cycold  has stated.

**Comment by gluons** [comment]
@KagamiChan Your code seems incorrect. `postcss-loader` shouldn't add at the last.

**From [`postcss-loader`'s docs](https://github.com/postcss/postcss-loader):**  
> Use it **after** `css-loader` and `style-loader`, but **before** other preprocessor loaders like e.g `sass|less|stylus-loader`, if you use any.

**Comment by KagamiChan** [comment]
@gluons agreed, you're right

**Comment by hanzhenlong** [comment]
@cycold I tried the solution but did not work
![image](https://user-images.githubusercontent.com/11323590/30999600-b722bae8-a508-11e7-8099-bba3475cf012.png)

 anyone can help? tks

**Comment by diachedelic** [comment]
I ran `vue init webpack my-project` just now, and was able to reproduce @fvsch 's 3rd example:

```html
<!-- src/App.vue -->
<style>
@import './assets/test1.css';
.test1b { display: flex; }
</style>

<style lang="scss">
@import './assets/test2.scss';
.test2b { display: flex; }
</style>
```

Result:

```css
/* dist/static/css/app.6c438b7dca17522bb707d18112b8cbcb.css */
.test1{display:flex}.test1b,.test2,.test2b{display:-webkit-box;display:-ms-flexbox;display:flex}
```

This is an issue for using 3rd party Vue components which import plain css.
